In [5]:
# sample input :
# 3 1000
# 2 5 4
# 3 7 8 9 
# 5 5 7 8 9 10 
# sample output 206
#--------------------
#    7 867
#    7 6429964 4173738 9941618 2744666 5392018 5813128 9452095
#    7 6517823 4135421 6418713 9924958 9370532 7940650 2027017
#    7 1506500 3460933 1550284 3679489 4538773 5216621 5645660
#    7 7443563 5181142 8804416 8726696 5358847 7155276 4433125
#    7 2230555 3920370 7851992 1176871 610460 309961 3921536
#    7 8518829 8639441 3373630 5036651 5291213 2308694 7477960
#    7 7178097 249343 9504976 8684596 6226627 1055259 4880436
#sample output => 866
from itertools import product
K,M = map(int,input().split())
result =0;
N = []
for j in range(K):
    q = list(map(int,input().split()[1:]))
    N.append(list(j**2 for j in q))
for l in product(*N):
    print(l)
print(max(list(sum(i)%M for i in product(*N))))

3 1000
2 5 4
3 7 8 9
5 5 7 8 9 10
(25, 49, 25)
(25, 49, 49)
(25, 49, 64)
(25, 49, 81)
(25, 49, 100)
(25, 64, 25)
(25, 64, 49)
(25, 64, 64)
(25, 64, 81)
(25, 64, 100)
(25, 81, 25)
(25, 81, 49)
(25, 81, 64)
(25, 81, 81)
(25, 81, 100)
(16, 49, 25)
(16, 49, 49)
(16, 49, 64)
(16, 49, 81)
(16, 49, 100)
(16, 64, 25)
(16, 64, 49)
(16, 64, 64)
(16, 64, 81)
(16, 64, 100)
(16, 81, 25)
(16, 81, 49)
(16, 81, 64)
(16, 81, 81)
(16, 81, 100)
206